name: stock_counter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.2+1
  tuple: ^2.0.0
  flutter_breadcrumb: ^1.0.1

  amplify_auth_cognito: ^0.4.0
  amplify_authenticator: ^0.1.0
  amplify_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  widgetbook: ^1.0.3
  flutter_lints: ^1.0.0
  grinder: ^0.9.0

flutter:
  uses-material-design: true